apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http          # <-- Add this name
    port: 80
    targetPort: 80
    protocol: TCP