apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - name: http          # <-- Add this name for Prometheus & Ingress
    port: 80
    targetPort: 8080
    protocol: TCP  