apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: development
type: Opaque
stringData:
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  MONGO_URI: "mongodb+srv://arunk:uRIpe7uOS7yfm3oW@cluster0.ctsgn0y.mongodb.net/orderDb?appName=Cluster0"
