apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - developer-readonly-clusterrole.yaml
  - developer-readonly-rolebinding.yaml
  - sre-clusterrole.yaml
  - sre-clusterrolebinding.yaml
  - sre-exec-role.yaml
  - sre-exec-rolebinding.yaml
