apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
  - name: http          # <-- Add this name
    port: 80
    targetPort: 8080
    protocol: TCP