apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: development
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-secrets
  data:
    - secretKey: REDIS_HOST
      remoteRef:
        key: microservices/dev/app-config
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: microservices/dev/app-config
        property: REDIS_PORT
